In [118]:
import numpy as np
import torch
np.random.seed(1234)
torch.manual_seed(1234)

In [119]:
x = np.random.randn(2,3)

In [120]:
print(x)

[[ 0.47143516 -1.19097569  1.43270697]
 [-0.3126519  -0.72058873  0.88716294]]


## Basics

In [121]:
x = torch.randn(2,3)  # normal distribution (rand(2,3) -> uniform distribution)
print(f"Type:{x.type()}")
print(f"Size:{x.shape}")
print(f"Values:\n{x}")

Type:torch.FloatTensor
Size:torch.Size([2, 3])
Values:
tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [122]:
x = torch.zeros(2,3)
print(x)
x= torch.ones(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [123]:
#list -> Tensor
x = torch.Tensor([[1,2,3],[4,5,6]])
print(f"Size:{x.shape}")
print(f"Values: \n{x}")

Size:torch.Size([2, 3])
Values: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [124]:
# Numpy array -> Tensor
x = torch.Tensor(np.random.rand(2,3))
print(f"Size: {x.shape}")
print(f"Values: \n{x}")

Size: torch.Size([2, 3])
Values: 
tensor([[0.2765, 0.8019, 0.9581],
        [0.8759, 0.3578, 0.5010]])


In [125]:
#Changing tensor type
x = torch.Tensor(3,4)
print(f"Type: {x.type()}")
x = x.long()
print(f"Type: {x.type()}")

Type: torch.FloatTensor
Type: torch.LongTensor


## Operations

In [126]:
#Addition
x = torch.randn(2,3)
y = torch.randn(2,3)
z = x+y
print(f"Size: {z.shape}")
print(f"Values: \n{z}")


Size: torch.Size([2, 3])
Values: 
tensor([[ 0.0761, -0.6775, -0.3988],
        [ 3.0633, -0.1589,  0.3514]])


In [127]:
x = torch.randn(2,3)
y = torch.randn(3,2)
z = torch.mm(x,y) # torch.t(x) for Transpose 
print(f"Size: {z.shape}")
print(f"Values: \n{z}")


Size: torch.Size([2, 2])
Values: 
tensor([[ 1.0796, -0.0759],
        [ 1.2746, -0.5134]])


In [128]:
#Reshape
x = torch.randn(2,3)
z = x.view(3,2)
print(f"Size: {z.shape}")
print(f"Values: \n{z}")

Size: torch.Size([3, 2])
Values: 
tensor([[ 0.8042, -0.1383],
        [ 0.3196, -1.0187],
        [-1.3147,  2.5228]])


In [129]:
x = torch.tensor([
    [[1,1,1,1], [2,2,2,2], [3,3,3,3]],
    [[10,10,10,10], [20,20,20,20], [30,30,30,30]]
])
print(f"Size: {x.shape}")
print(f"x: \n{x}\n")

a = x.view(x.size(1), -1)
print(f"\nSize: {a.shape}")
print(f"a: \n{a}\n")

b = x.transpose(0,1).contiguous()
print(f"\nSize: {b.shape}")
print(f"b: \n{b}\n")

c = b.view(b.size(1), -1)
print(f"\nSize: {c.shape}")
print(f"c: \n{c}")




Size: torch.Size([2, 3, 4])
x: 
tensor([[[ 1,  1,  1,  1],
         [ 2,  2,  2,  2],
         [ 3,  3,  3,  3]],

        [[10, 10, 10, 10],
         [20, 20, 20, 20],
         [30, 30, 30, 30]]])


Size: torch.Size([3, 8])
a: 
tensor([[ 1,  1,  1,  1,  2,  2,  2,  2],
        [ 3,  3,  3,  3, 10, 10, 10, 10],
        [20, 20, 20, 20, 30, 30, 30, 30]])


Size: torch.Size([3, 2, 4])
b: 
tensor([[[ 1,  1,  1,  1],
         [10, 10, 10, 10]],

        [[ 2,  2,  2,  2],
         [20, 20, 20, 20]],

        [[ 3,  3,  3,  3],
         [30, 30, 30, 30]]])


Size: torch.Size([2, 12])
c: 
tensor([[ 1,  1,  1,  1, 10, 10, 10, 10,  2,  2,  2,  2],
        [20, 20, 20, 20,  3,  3,  3,  3, 30, 30, 30, 30]])


In [130]:
#Dimensional operations
x = torch.randn(2,3)
print(f"Values: \n{x}")
y = torch.sum(x, dim=0)
print(f"Values: \n{y}")
z = torch.sum(x, dim=1) # add each columns's value for every row
print(f"Values: \n{z}")

Values: 
tensor([[ 0.4501,  0.2709, -0.8087],
        [-0.0217, -1.0413,  0.0702]])
Values: 
tensor([ 0.4284, -0.7704, -0.7385])
Values: 
tensor([-0.0877, -0.9928])


In [136]:
x = torch.randn(3,4)
print(f"Values: \n{x}")

indices = torch.LongTensor([0,2])
chosen1 = torch.index_select(x, dim=0, index=indices) # rows
chosen2 = torch.index_select(x, dim=1, index=indices) # colums
print(f"Values: \n{chosen1}")
print(f"Values: \n{chosen2}")

row_indices = torch.LongTensor([0,1])
col_indices = torch.LongTensor([0,2])
chosen = x[row_indices, col_indices] # values from (0, 0) & (1, 2)
print(f"Values: \n{chosen}")


Values: 
tensor([[ 1.4696, -1.3284,  1.9946, -0.8209],
        [ 1.0061, -1.0664, -0.4572,  0.0901],
        [ 0.4018, -1.1542,  0.1192, -0.7348]])
Values: 
tensor([[ 1.4696, -1.3284,  1.9946, -0.8209],
        [ 0.4018, -1.1542,  0.1192, -0.7348]])
Values: 
tensor([[ 1.4696,  1.9946],
        [ 1.0061, -0.4572],
        [ 0.4018,  0.1192]])
Values: 
tensor([ 1.4696, -0.4572])


In [137]:
x = torch.randn(2,3)
print(x)
print(x.shape)

tensor([[-1.5864, -0.2671,  2.6874],
        [-0.4633,  0.6639,  0.2383]])
torch.Size([2, 3])


In [146]:
#Concatenation
y = torch.cat([x,x], dim=1)
print(y)
print(y.shape)

tensor([[-1.5864, -0.2671,  2.6874, -1.5864, -0.2671,  2.6874],
        [-0.4633,  0.6639,  0.2383, -0.4633,  0.6639,  0.2383]])
torch.Size([2, 6])


In [149]:
#Stacking
z = torch.stack([x,x], dim=1)
print(z)
print(z.shape)

tensor([[[-1.5864, -0.2671,  2.6874],
         [-1.5864, -0.2671,  2.6874]],

        [[-0.4633,  0.6639,  0.2383],
         [-0.4633,  0.6639,  0.2383]]])
torch.Size([2, 2, 3])


In [163]:
x= torch.randn(3,4, requires_grad=True)
y = 3*x + 2
z = y.mean()
z.backward()
print(f"x: \n{x}")
print(f"x.grad: \n{x.grad}")



x: 
tensor([[ 1.9117,  1.9975,  0.2659,  0.7959],
        [-0.4948,  1.4177,  1.1192,  0.4914],
        [ 0.8575, -0.4515,  0.7116, -0.7046]], requires_grad=True)
x.grad: 
tensor([[0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500],
        [0.2500, 0.2500, 0.2500, 0.2500]])


In [164]:
print(torch.cuda.is_available())

False
